name: Kitchen Terraform Action
description: Run kitchen-terraform commands
branding:
  icon: arrow-left
  color: gray-dark
inputs:
  kitchen-command:
    description: "The command to run for example: help"
    required: true
    default: help
runs:
  using: docker
  image: docker://ghcr.io/osinfra-io/github-kitchen-terraform-action:latest
  args:
    - ${{ inputs.kitchen-command }}
