# Metadata for GitHub Actions
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Kitchen-Terraform Github Action
author: osinfra.io
description: Run kitchen-terraform commands
branding:
  icon: terminal
  color: gray-dark
inputs:
  kitchen-command:
    description: "The command to run for example: help"
    required: true
    default: help
  kitchen-instance:
    description: "The instance to run the command on"
    required: false
runs:
  using: docker
  image: docker://ghcr.io/osinfra-io/github-kitchen-terraform-action:latest
  args:
    - ${{ inputs.kitchen-command }}
