# Metadata for GitHub Actions
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Kitchen-Terraform Github Action
author: osinfra.io
description: Run kitchen-terraform commands
branding:
  icon: arrow-left
  color: gray-dark
inputs:
  kitchen-command:
    description: "The command to run for example: help"
    required: true
    default: help
runs:
  using: docker
  image: docker://faisalshah/kitchen-terraform:latest
  args:
    - ${{ inputs.kitchen-command }}
